# course_data.py
#
# This is OUR OWN curated course mapping table — not generated by Gemini.
# Each skill maps to 1-2 real, verified courses from PIAIC, Saylani,
# Coursera, Udemy, or YouTube.
#
# Why this exists separately from the Gemini prompt:
# Gemini is used only to read the CV/JD and figure out which skills are
# missing or partial. Once we know WHICH skills are missing, WE decide
# which courses to recommend — using this table — instead of asking
# Gemini to invent course names/URLs (which risks hallucinated/broken links).

COURSE_MAP = {

    # ── Programming Languages ──
    "python": [
        {
            "platform": "PIAIC",
            "name": "PIAIC AI & Data Science Program (Python foundations)",
            "url": "https://www.piaic.org/",
            "duration": "1 quarter (3 months)",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "YouTube",
            "name": "Python Full Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
            "duration": "4.5 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "sql": [
        {
            "platform": "YouTube",
            "name": "SQL Tutorial - Full Database Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
            "duration": "4 hours",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Coursera",
            "name": "SQL for Data Science — UC Davis (Coursera, free to audit)",
            "url": "https://www.coursera.org/learn/sql-for-data-science",
            "duration": "4 weeks",
            "free": True,
            "level": "Beginner"
        }
    ],

    "javascript": [
        {
            "platform": "YouTube",
            "name": "JavaScript Full Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
            "duration": "3.5 hours",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Saylani",
            "name": "Saylani Mass IT Training — Web & Mobile Application Development",
            "url": "https://www.saylanimit.com/courses",
            "duration": "6 months",
            "free": True,
            "level": "Beginner"
        }
    ],

    "java": [
        {
            "platform": "YouTube",
            "name": "Java Full Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=xk4_1vDrzzo",
            "duration": "12 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "c++": [
        {
            "platform": "YouTube",
            "name": "C++ Full Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=8jLOx1hD3_o",
            "duration": "4 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "r programming": [
        {
            "platform": "YouTube",
            "name": "R Programming for Data Science — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=_V8eKsto3Ug",
            "duration": "12 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    # ── Web Development ──
    "react": [
        {
            "platform": "YouTube",
            "name": "React Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=bMknfKXIFA8",
            "duration": "11 hours",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Saylani",
            "name": "Saylani Mass IT Training — Web & Mobile Application Development",
            "url": "https://www.saylanimit.com/courses",
            "duration": "6 months",
            "free": True,
            "level": "Intermediate"
        }
    ],

    "node.js": [
        {
            "platform": "YouTube",
            "name": "Node.js and Express.js Full Course — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=Oe421EPjeBE",
            "duration": "8 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "html css": [
        {
            "platform": "YouTube",
            "name": "HTML and CSS Full Course — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=mU6anWqZJcc",
            "duration": "11 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "git": [
        {
            "platform": "YouTube",
            "name": "Git and GitHub for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=RGOj5yH7evk",
            "duration": "1 hour",
            "free": True,
            "level": "Beginner"
        }
    ],

    # ── Data Analytics / Data Science ──
    "power bi": [
        {
            "platform": "YouTube",
            "name": "Power BI Full Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=AGrl-H87pRU",
            "duration": "4 hours",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Coursera",
            "name": "Microsoft Power BI Data Analyst Professional Certificate",
            "url": "https://www.coursera.org/professional-certificates/microsoft-power-bi-data-analyst",
            "duration": "5 months",
            "free": True,
            "level": "Beginner"
        }
    ],

    "tableau": [
        {
            "platform": "YouTube",
            "name": "Tableau Full Course for Beginners — Edureka",
            "url": "https://www.youtube.com/watch?v=aHaOIvR00So",
            "duration": "10 hours",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Coursera",
            "name": "Data Visualization with Tableau — UC Davis",
            "url": "https://www.coursera.org/specializations/data-visualization",
            "duration": "5 months",
            "free": True,
            "level": "Beginner"
        }
    ],

    "excel": [
        {
            "platform": "YouTube",
            "name": "Excel Full Course for Beginners — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=Vl0H-qTclOg",
            "duration": "3.5 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "statistics": [
        {
            "platform": "YouTube",
            "name": "Statistics Full Course — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=xxpc-HPKN28",
            "duration": "8 hours",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Coursera",
            "name": "Statistics with Python — University of Michigan",
            "url": "https://www.coursera.org/specializations/statistics-with-python",
            "duration": "5 months",
            "free": True,
            "level": "Beginner"
        }
    ],

    "machine learning": [
        {
            "platform": "PIAIC",
            "name": "PIAIC AI & Data Science Program",
            "url": "https://www.piaic.org/",
            "duration": "1 year (4 quarters)",
            "free": True,
            "level": "Intermediate"
        },
        {
            "platform": "Coursera",
            "name": "Machine Learning Specialization — Andrew Ng (DeepLearning.AI / Stanford)",
            "url": "https://www.coursera.org/specializations/machine-learning-introduction",
            "duration": "3 months",
            "free": True,
            "level": "Intermediate"
        }
    ],

    "data visualization": [
        {
            "platform": "YouTube",
            "name": "Data Visualization with Python — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=a9UrKTVEeZA",
            "duration": "4 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "data analysis": [
        {
            "platform": "Coursera",
            "name": "Google Data Analytics Professional Certificate",
            "url": "https://www.coursera.org/professional-certificates/google-data-analytics",
            "duration": "6 months",
            "free": True,
            "level": "Beginner"
        },
        {
            "platform": "Saylani",
            "name": "Saylani Mass IT Training — Data Science / AI track",
            "url": "https://www.saylanimit.com/courses",
            "duration": "6 months",
            "free": True,
            "level": "Beginner"
        }
    ],

    # ── Cloud / DevOps ──
    "cloud computing": [
        {
            "platform": "PIAIC",
            "name": "PIAIC Cloud Native Computing with Kubernetes Program",
            "url": "https://www.piaic.org/",
            "duration": "1 year (4 quarters)",
            "free": True,
            "level": "Intermediate"
        },
        {
            "platform": "YouTube",
            "name": "AWS Cloud Practitioner Full Course — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=SOTamWNgDKc",
            "duration": "13 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    "docker": [
        {
            "platform": "YouTube",
            "name": "Docker Full Course — freeCodeCamp",
            "url": "https://www.youtube.com/watch?v=fqMOX6JJhGo",
            "duration": "2.5 hours",
            "free": True,
            "level": "Beginner"
        }
    ],

    # ── Soft / professional skills (templated, not course-based) ──
    "communication skills": [
        {
            "platform": "Coursera",
            "name": "Improving Communication Skills — University of Pennsylvania",
            "url": "https://www.coursera.org/learn/wharton-communication-skills",
            "duration": "4 weeks",
            "free": True,
            "level": "Beginner"
        }
    ],

    "project management": [
        {
            "platform": "Coursera",
            "name": "Google Project Management Professional Certificate",
            "url": "https://www.coursera.org/professional-certificates/google-project-management",
            "duration": "6 months",
            "free": True,
            "level": "Beginner"
        }
    ],
}


# Synonyms / common variations -> canonical key used in COURSE_MAP above.
# This is what makes matching resilient to how skills are phrased in a
# real Gemini response (e.g. "PowerBI", "Power-BI", "MS Excel" etc.)
SKILL_ALIASES = {
    "powerbi": "power bi",
    "power-bi": "power bi",
    "ms excel": "excel",
    "microsoft excel": "excel",
    "excel (pivot tables, vlookup, formulas)": "excel",
    "sql and relational databases": "sql",
    "relational databases": "sql",
    "version control": "git",
    "version control (git)": "git",
    "github": "git",
    "ml": "machine learning",
    "react.js": "react",
    "reactjs": "react",
    "nodejs": "node.js",
    "node": "node.js",
    "html/css": "html css",
    "html & css": "html css",
    "data viz": "data visualization",
    "statistical concepts": "statistics",
    "stats": "statistics",
    "python for data analysis": "python",
    "aws": "cloud computing",
    "azure": "cloud computing",
    "gcp": "cloud computing",
}


def get_courses_for_skill(skill_name: str):
    """
    Look up courses for a given skill string returned by Gemini.
    Falls back to checking aliases, then partial keyword matching,
    then a generic fallback if nothing matches.
    """
    key = skill_name.strip().lower()

    # Direct match
    if key in COURSE_MAP:
        return COURSE_MAP[key]

    # Alias match
    if key in SKILL_ALIASES:
        return COURSE_MAP.get(SKILL_ALIASES[key], [])

    # Partial match — e.g. "Strong knowledge of SQL and relational databases"
    # should still match "sql"
    for known_skill in COURSE_MAP:
        if known_skill in key:
            return COURSE_MAP[known_skill]
    for alias, canonical in SKILL_ALIASES.items():
        if alias in key:
            return COURSE_MAP.get(canonical, [])

    # Fallback — generic YouTube search link, always works even for
    # skills we haven't manually curated yet
    return [{
        "platform": "YouTube",
        "name": f"Search: {skill_name} tutorial for beginners",
        "url": f"https://www.youtube.com/results?search_query={skill_name.replace(' ', '+')}+tutorial+for+beginners",
        "duration": "Varies",
        "free": True,
        "level": "Beginner"
    }]